project:
  type: website
  output-dir: docs
  

website:
  title: "Research Methods in Political Science"
  sidebar:
    background: primary
    logo: "images/ps0700_logo-modified.png"
    pinned: true
    align: center
    style: docked
    contents:
      - href: syllabus.qmd
        text: Syllabus
      - href: materials.qmd
        text: Materials
      - href: https://www.stevenfinkel.com/teaching.html
        text: "Other Courses"

format:
  html:
    anchor-sections: false
    page-layout: full
    theme:
      light: flatly
      dark: darkly
    theme-toggle: true
    tools:
      - toggle
    css: styles.css
    toc: true
    include-in-header: "_includes/google-verify.html"
    
editor: visual

