---
title: "Research Methods in Political Science"
author: "<a href='https://finkel-s.github.io/about.html' target='_blank'><strong>Steven E. Finkel</strong></a><br><a href='mailto:finkel@pitt.edu'>📧 finkel@pitt.edu</a>"
format:
  html:
    toc: true
    toc-depth: 2
    number-sections: false
    css: styles.css
---

## Course Description

::: justify-text
This course serves as an introduction to the methodology of political science research. The course will begin with the logic of social scientific inquiry and the basics of research design, and then introduce students to the quantitative and qualitative methods that are commonly used by political scientists to investigate important questions about the political world.

The goals of the course are:

1.  For the student to become both an intelligent consumer of quantitative and qualitative research, with the ability to see the strengths and flaws of social scientific studies in academic journals and books, newspapers, websites, and other outlets.\
2.  To give students the skills necessary to begin conducting original political science research studies of their own.

By the end of the class, students will have developed a critical understanding of issues related to scientific inquiry, measurement, causal inference, experimental, quasi-experimental and observational research, formal modeling, comparative research, sampling and survey research, focus groups, in-depth interviewing, case studies and other qualitative methods of data collection.

Students will also learn fundamental concepts in descriptive and inferential statistics, and in data analytic techniques such as crosstabulation, correlation and regression analysis, and will develop the skills to apply these methods using the R statistical package.
:::

## Texts

::: justify-text
-   Kellstedt, Paul M. and Guy D. Whitten. 2018. *The Fundamentals of Political Science Research*, 3rd Edition. Cambridge: Cambridge University Press.

Students will be using **R** for learning the various statistical techniques and for conducting the research exercise. We'll provide step-by-step instructions in using R as the course progresses. You can find general introductions in:

-   Imai, Kosuke. 2017. *Quantitative Social Science: An Introduction*, Princeton University Press.
-   Wickham, Hadley, Mine Çetinkaya-Rundel, and Garrett Grolemund. 2023. *R for Data Science* (2nd ed.). O'Reilly Media. Available at: <https://r4ds.hadley.nz/>.
:::

## Course Requirements

::: justify-text
Grades will be based on three exams, one research exercise, and participation in class discussion and the recitation section. The first two exams will be held in-class, and the last exam will be held at the normal scheduled time during finals week.

The research exercise will be an approximately seven-page paper in which you:

-   Specify hypothesized relationships between political variables;
-   Use R to test the hypotheses with quantitative methods on data that will be made available to you; and,
-   Interpret the results of the analyses.
:::

## Course Outline

::: justify-text
The course is organized by units and then topics within units. We will maintain a certain amount of flexibility with the schedule, so that we can spend more time on some topics/units and scale back on others as circumstances warrant.

### Unit 1: The Nuts and Bolts of Political 'Science'

#### 1. [Introduction to the Course](materials.html#introduction-to-the-course)

-   Kellstedt, Paul M. and Guy D. Whitten. 2018. *The Fundamentals of Political Science Research*, 3rd ed. Cambridge: Cambridge University Press, Chapter 1.

#### 2. [Political Science as a "Science"](materials.html#political-science-as-a-science)

-   Easton, David. 1991. "Political Science in the United States: Past and Present." In *Divided Knowledge: Across Disciplines, Across Cultures*, eds. David Easton and Corinne Schelling. Sage Publications.\
-   Kasza, Gregory J. 2001. "Perestroika: For an Ecumenical Science of Politics." *PS: Political Science & Politics* 34(3): 597--599.\
-   Bennett, Andrew. 2002. "Perestroika Lost: Why the Latest 'Reform' Movement in Political Science Should Fail." *PS: Political Science & Politics* 35(2): 177--179.

##### *Recitation*: Is Political Science a Science?

-   <a href="https://www.nytimes.com/2009/10/20/books/20poli.html?_r=1" target="_blank">"Just How Relevant is Political Science?"</a> *New York Times*, October 19, 2009.\
-   <a href="https://blogs.scientificamerican.com/cross-check/is-social-science-an-oxymoron-will-that-ever-change/" target="_blank">"Is 'Social Science' an Oxymoron?"</a> *Scientific American*, April 4, 2013.\
-   <a href="https://www.washingtonpost.com/news/monkey-cage/wp/2017/10/04/justice-roberts-said-political-science-is-sociological-gobbledygook-heres-why-he-said-it-and-why-hes-mistaken/" target="_blank">"Justice Roberts Said Political Science is 'Sociological Gobbledygook.'"</a> *Washington Post*, October 4, 2017.

#### 3. [Theories, Hypotheses, Variables](materials.html#theories-hypotheses-variables)

-   Kellstedt, Paul M. and Guy D. Whitten. 2018. *The Fundamentals of Political Science Research*, 3rd ed. Cambridge: Cambridge University Press, Chapters 2 and 5.
-   Weber, Erik. 2022. "On Laws of Politics and How to Establish Them." *PS: Political Science & Politics* 55(3): 457--461.

#### 4. [Measurement](materials.html#measurement)

-   Kellstedt, Paul M. and Guy D. Whitten. 2018. *The Fundamentals of Political Science Research*, 3rd ed. Cambridge: Cambridge University Press, Chapter 3.\
-   Sullivan, John L., James Piereson, and George E. Marcus. 1979. "An Alternative Conceptualization of Political Tolerance: Illusory Increases: 1950s--1970s." *American Political Science Review* 73(3): 781--794.\
-   Lührmann, Anna, et al. 2018. "Regimes of the World (RoW): Opening New Avenues for the Comparative Study of Political Regimes." *Politics and Governance* 6(1): 60--77.

##### *Recitation*: Theory, Variables, and Measurement in Political Science

-   <a href="http://www.nytimes.com/2014/08/28/opinion/nicholas-kristof-is-everyone-a-little-bit-racist.html?hp&action=click&pgtype=Homepage&module=c-column-top-span-region&region=c-column-top-span-region&WT.nav=c-column-top-span-region&_r=0" target="_blank">"Is Everyone a Little Bit Racist?"</a> *New York Times*, August 28, 2014.\
-   <a href="https://www.almendron.com/tribuna/the-bogus-science-of-secondhand-smoke/" target="_blank">"The Bogus 'Science' of Second Hand Smoke."</a> *Washington Post*, January 30, 2007.\
-   <a href="https://www.nytimes.com/2022/04/29/world/asia/south-korea-age-yoon.html?referringSource=articleShare" target="_blank">"Millions of South Koreans Could Soon Get Younger (On Paper)."</a> *New York Times*, April 29, 2022.\
-   <a href="https://www.nytimes.com/2021/09/30/us/police-killings-undercounted-study.html?referringSource=articleShare" target="_blank">"More Than Half of Police Killings Are Mislabeled, New Study Says."</a> *New York Times*, September 30, 2021.\
-   <a href="https://www.nytimes.com/2021/05/15/opinion/noise-bias-kahneman.html?action=click&module=Opinion&pgtype=Homepage" target="_blank">"Bias Is a Big Problem. But So is 'Noise.'"</a> *New York Times*, May 15, 2021.

### Unit 2: Research Designs in Political Science

#### 1. [Causality](materials.html#causality)

-   Kellstedt, Paul M. and Guy D. Whitten. 2018. *The Fundamentals of Political Science Research*, 3rd ed. Cambridge: Cambridge University Press, Chapter 4.\
-   Bueno de Mesquita, Ethan and Anthony Fowler. 2021. "Causation: What Is It and What Is It Good For?" In *Thinking clearly with data: a guide to quantitative reasoning and analysis*. Princeton: Princeton University Press.

#### 2. [Experimental Designs](materials.html#experimental-designs)

-   Bueno de Mesquita, Ethan and Anthony Fowler. 2021. "Randomized Experiments." In *Thinking clearly with data: a guide to quantitative reasoning and analysis*. Princeton: Princeton University Press.
-   Iyengar, Shanto, Mark D. Peters, and Donald R. Kinder. 1982. "Experimental Demonstrations of the 'Not-So-Minimal' Consequences of Television News Programs." *American Political Science Review* 76(4): 848--858. *\[Lab Experiment\]*
-   Gerber, Alan S. and Donald P. Green. 2000. "The Effects of Canvassing, Telephone Calls, and Direct Mail on Voter Turnout: A Field Experiment." *American Political Science Review* 94(3): 653--663. *\[Field Experiment\]*

##### *Recitation*: Causality and Experimentation in Political Science

-   <a href="http://www.slate.com/articles/business/crosspollination/2014/03/randomized_controlled_trials_do_they_work_for_economic_development.html" target="_blank">"Random Acts: What Happens When You Approach Global Poverty as a Science Experiment"</a>, *Slate*, March 26, 2014.\
-   <a href="http://www.slate.com/articles/health_and_science/science/2014/06/facebook_unethical_experiment_it_made_news_feeds_happier_or_sadder_to_manipulate.html" target="_blank">"Facebook's Unethical Experiment"</a>, *Slate*, June 28, 2014.\
-   <a href="https://www.nytimes.com/2014/10/29/upshot/professors-research-project-stirs-political-outrage-in-montana.html" target="_blank">"Professors' Research Project Stirs Political Outrage in Montana"</a>, *New York Times*, October 18, 2014.\
-   <a href="https://www.washingtonpost.com/opinions/2019/12/03/what-would-happen-if-we-randomly-gave-poor-families-now-we-know/" target="_blank">"What Would Happen if We Randomly Gave \$1,000 to Poor Families? Now We Know"</a>, *Washington Post*, March 12, 2019.\
-   <a href="https://www.nytimes.com/2018/11/19/science/science-research-fraud-reproducibility.html" target="_blank">"The Experiments Are Fascinating. But Nobody Can Repeat Them"</a>, *New York Times*, November 19, 2018.

#### 3. [Quasi-Experiments](materials.html#quasi-experiments)

-   Posner, Daniel N. 2004. "The Political Salience of Cultural Difference: Why Chewas and Tumbukas Are Allies in Zambia and Adversaries in Malawi." *American Political Science Review* 98(3): 529--545. *\[Natural Experiment\]*
-   Hopkins, Daniel J. and Katherine T. McCabe. 2012. "After It's Too Late: Estimating the Policy Impacts of Black Mayoralities in U.S. Cities." *American Politics Research* 40(4): 665--700. *\[Regression Discontinuity\]*
-   Sønderskov, Kim Mannemar, Peter Thisted Dinesen, Steven E. Finkel, and Kasper M. Hansen. 2022. "Crime Victimization Increases Turnout: Evidence from Individual-Level Administrative Panel Data." *British Journal of Political Science* 52(1): 399--407. *\[Difference-in-Differences\]*

#### 4. [Observational Designs](materials.html#observational-designs)

-   Finkel, Steven E. 1985. "Reciprocal Effects of Political Participation and Political Efficacy: A Panel Analysis." *American Journal of Political Science* 29(4): 891--913. *\[Panel Analysis\]*\
-   MacKuen, Michael B., Robert S. Erikson, and James A. Stimson. 1989. "Macropartisanship." *American Political Science Review* 83(4): 1125--1142. *\[Time Series Analysis\]*
-   Dalton, Russell, Alix Van Sickle, and Steven Weldon. 2010. "The Individual-Institutional Nexus of Protest Behavior." *British Journal of Political Science* 40(1): 51--73. *\[Multilevel Analysis\]*

##### *Recitation*: Quasi-Experiments and Observational Research in Political Science

-   <a href="https://www.nytimes.com/2018/03/12/well/family/why-demonstrating-is-good-for-kids.html" target="_blank">"Why Demonstrating Is Good for Kids"</a>, *New York Times*, March 12, 2018.\
-   <a href="https://www.nytimes.com/2018/01/30/upshot/do-fast-and-furious-movies-cause-a-rise-in-speeding.html" target="_blank">"Do 'Fast and Furious' Movies Cause a Rise in Speeding?"</a>, *New York Times*, January 30, 2018.\
-   <a href="https://www.washingtonpost.com/outlook/2021/08/31/covid-israel-hospitalization-rates-simpsons-paradox/" target="_blank">"Coronavirus Vaccines Work. But This Statistical Illusion Makes People Think They Don't"</a>, *Washington Post*, August 31, 2021.\
-   <a href="https://www.nytimes.com/2013/06/16/magazine/study-women-denied-abortions.html" target="_blank">"What Happens to Women Who Are Denied Abortions"</a>, *New York Times*, June 12, 2013. *(referencing* <a href="https://www.ansirh.org/research/ongoing/turnaway-study" target="_blank">The Turnaway Study</a>)\
-   <a href="https://time.com/6045637/not-prosecuting-misdemeanors-reduce-crime/" target="_blank">"A New Study Reveals That Not Prosecuting People for Nonviolent Misdemeanors May Actually Reduce Crime"</a>, *Time*, May 4, 2021.

### Unit 3: Research Designs II --- Formal, Comparative, and Qualitative Approaches

#### 1. [Rational Choice and Formal Modeling](materials.html#rational-choice-and-formal-modeling)

-   Johnson, Janet Buttolph and H.T. Reynolds. 2012. "Formal Modeling and Simulation." In *Political Science Research Methods*, 7th ed. CQ Press, pp. 207--213.\
-   Riker, William H. 1990. "Political Science and Rational Choice." Chapter. In Perspectives on Positive Political Economy, edited by James E. Alt and Kenneth A. Shepsle, 163--81. Cambridge: Cambridge University Press.\
-   Stewart, Charles. 2001. *Analyzing Congress*. W. W. Norton & Company, Chapter 1, pp. 3--22.

##### *Recitation*: Rational Choice Models in Political Science

-   <a href="http://www.slate.com/id/2212340/pagenum/all/" target="_blank">"The 10 Cunning Ways Public Radio Stations Convince You to Give Them Money"</a>, *Slate*, March 2, 2009.\
-   <a href="https://www.newyorker.com/news/our-columnists/how-game-theory-explains-the-leaks-in-the-trump-white-house" target="_blank">"How Game Theory Explains the Leaks in the Trump White House"</a>, *The New Yorker*, May 15, 2018.\
-   <a href="https://www.nytimes.com/2020/12/20/health/virus-vaccine-game-theory.html?referringSource=articleShare" target="_blank">"The Pandemic is a Prisoner's Dilemma Game"</a>, *New York Times*, December 20, 2020.\
-   <a href="https://www.nytimes.com/2010/02/07/business/economy/07view.html?searchResultPosition=1" target="_blank">"Why Politics Is Stuck in the Middle"</a>, *New York Times*, February 6, 2010.\
-   <a href="https://www.washingtonpost.com/politics/interactive/2021/ranked-choice-voting-guide/" target="_blank">"How Ranked Choice Voting Could Change the Way Democracy Works"</a>, *Washington Post*, June 21, 2021.

#### 2. [Comparative and Qualitative Research](materials.html#comparative-and-qualitative-research)

-   Johnson, Janet Buttolph and H.T. Reynolds. 2012. *Political Science Research Methods*. CQ Press, Chapter 10.\
-   Peters, B. Guy. 1998. "The Logic of Comparison." In *Comparative Politics: Theory and Method*. New York University Press.\
-   Bennett, Andrew and Colin Elman. 2007. "Case Study Methods in the International Relations Subfield." *Comparative Political Studies* 40(2): 170-195.\
-   Davies, Peter. 2004. "Qualitative Research and Evaluation: How Do You Know Why (and How) Something Works?" Chapter 8 in *The Magenta Book: Guidance Notes for Policy Evaluation and Analysis*. Government Chief Social Researcher's Office (UK).

##### *Recitation*: Comparative and Qualitative Analysis

-   <a href="https://slate.com/news-and-politics/2015/01/why-was-tunisia-the-only-arab-spring-country-that-turned-out-well.html" target="_blank">"Why Was Tunisia the Only Arab Spring Country That Turned Out Well?"</a>, *Slate*, January 28, 2015.\
-   <a href="https://www.nytimes.com/2022/04/12/opinion/conservative-voters-america.html?referringSource=articleShare" target="_blank">"These Eight Conservative Men Are Making No Apologies"</a>, *New York Times*, April 12, 2022.\
-   <a href="https://nytimesineducation.com/what-explains-u-s-mass-shootings-international-comparisons-suggest-an-answer/" target="_blank">"What Explains U.S. Mass Shootings? International Comparisons Suggest an Answer"</a>, *New York Times*, November 7, 2017.\
-   <a href="https://www.nytimes.com/2022/05/15/world/australia/covid-deaths.html?referringSource=articleShare" target="_blank">"How Australia Saved Thousands of Lives While Covid Killed a Million Americans"</a>, *New York Times*, May 15, 2022.

### Unit 4: Data Collection Strategies

#### 1. [Survey Research](materials.html#survey-research)

-   Johnson, Janet Buttolph and H.T. Reynolds. 2012. *Political Science Research Methods*, Chapter 10.\
-   Blair, Graeme, C. Christine Fair, Neil Malhotra, and Jacob N. Shapiro. 2013. "Poverty and Support for Militant Politics: Evidence from Pakistan." *American Journal of Political Science* 57(1): 30--48.\
-   Montalvo, J. Daniel, Georgina Pizzolitto, and Luke Plutowski. 2022. *Telephone Sampling in the 2021 AmericasBarometer: Methodological Note*. Latin American Public Opinion Project (LAPOP), Vanderbilt University.

#### 2. [Content Analysis and Big Data](materials.html#content-analysis-and-big-data)

-   Jungherr, Andreas and Yannis Theocharis. 2017. "The Empiricist's Challenge: Asking Meaningful Questions in Political Science in The Age of Big Data." *Journal of Information Technology & Politics* 14(2): 97--109.\
-   Nagler, Jonathan and Joshua A. Tucker. 2015. "Drawing Inferences and Testing Theories with Big Data." *PS: Political Science & Politics* 48(1): 84--88.

##### *Recitation*: Survey Research and Big Data in Political Science

-   <a href="https://www.washingtonpost.com/politics/2020-poll-errors/2021/07/18/8d6a9838-e7df-11eb-ba5d-55d3b5ffcaf1_story.html" target="_blank">"2020 Presidential Polls Suffered Worst Performance in Decades."</a> *New York Times*, July 18, 2021.\
-   <a href="https://www.washingtonpost.com/politics/2022/05/07/american-abortion-feelings-polling/" target="_blank">"Why It's So Difficult to Poll Americans' Feelings About Abortion."</a> *Washington Post*, May 7, 2022.\
-   <a href="https://www.washingtonpost.com/technology/2022/01/06/jan6-algorithms-prediction-violence/" target="_blank">"The Battle to Prevent Another January 6 Features a New Weapon: The Algorithm."</a> *Washington Post*, January 6, 2022.\
-   <a href="https://www.nytimes.com/2014/04/07/opinion/eight-no-nine-problems-with-big-data.html" target="_blank">"Eight (No, Nine!) Problems with Big Data."</a> *New York Times*, April 6, 2014.\
-   <a href="https://www.theguardian.com/commentisfree/2018/mar/05/algorithms-rate-credit-scores-finances-data" target="_blank">"The Tyranny of Algorithms Is Part of Our Lives: Soon They Could Rate Everything We Do."</a> *The Guardian*, March 5, 2018.

### Unit 5: Basic Statistical Methods

#### 1. [Descriptive Statistics and Introduction to Inference](materials.html#descriptive-statistics)

-   Kellstedt, Paul M. and Guy D. Whitten. 2018. *The Fundamentals of Political Science Research*, 3rd ed. Cambridge: Cambridge University Press, Chapter 6.\
-   Parikh, Ravi. 2014. "How to Lie with Data Visualization." *Heap Blog*, April 14.

#### 2. [Statistical Inference and Hypothesis Testing](materials.html#statistical-inference)

-   Kellstedt, Paul M. and Guy D. Whitten. 2018. *The Fundamentals of Political Science Research*, 3rd ed. Cambridge: Cambridge University Press, Chapter 7.

#### 3. [Cross-Tabulation](materials.html#cross-tabulation)

-   Kellstedt, Paul M. and Guy D. Whitten. 2018. *The Fundamentals of Political Science Research*, 3rd ed. Cambridge: Cambridge University Press, Chapter 7.

#### 4. [Correlation and Regression](materials.html#correlation-and-regression)

-   Kellstedt, Paul M. and Guy D. Whitten. 2018. *The Fundamentals of Political Science Research*, 3rd ed. Cambridge: Cambridge University Press, Chapter 8.

#### 5. [Multivariate Analysis](materials.html#multivariate-analysis)

-   Kellstedt, Paul M. and Guy D. Whitten. 2018. *The Fundamentals of Political Science Research*, 3rd ed. Cambridge: Cambridge University Press, Chapters 9 and 10.\
-   Lewis-Beck, Colin, and Michael Lewis-Beck. 2016. *Applied Regression: An Introduction*. 2nd ed., Thousand Oaks, CA: Sage Publications, Inc., pp. 9--46.

#### 6. Advanced Topics in Quantitative Methods

-   Kellstedt, Paul M. and Guy D. Whitten. 2018. *The Fundamentals of Political Science Research*, 3rd ed. Cambridge: Cambridge University Press, Chapters 11 and 12.
:::
